/// Countries / portfolios the EB can pick from when building the GSL.
///
/// Dummy list of the portfolios that turn up most often at MUNs. Add more names
/// here (any order, any spelling you want shown) and they appear automatically in
/// the EB Tools suggestions.
const List<String> kMunCountries = [
  'Afghanistan',
  'Argentina',
  'Australia',
  'Bangladesh',
  'Belgium',
  'Brazil',
  'Canada',
  'Chile',
  'China',
  'Colombia',
  'Cuba',
  'Denmark',
  'Egypt',
  'Ethiopia',
  'France',
  'Germany',
  'Ghana',
  'Greece',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Japan',
  'Kenya',
  'Malaysia',
  'Mexico',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nigeria',
  'North Korea',
  'Norway',
  'Pakistan',
  'Palestine',
  'Philippines',
  'Poland',
  'Qatar',
  'Russia',
  'Saudi Arabia',
  'Singapore',
  'South Africa',
  'South Korea',
  'Spain',
  'Sri Lanka',
  'Sweden',
  'Switzerland',
  'Syria',
  'Thailand',
  'Turkey',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States of America',
  'Venezuela',
  'Vietnam',
];
